events {}

http {
  server {
    listen 80;

    server_name _;

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
      proxy_pass http://127.0.0.1:3000;

      proxy_http_version 1.1;

      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";

      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

    location /_next/static/ {
      alias /app/.next/static/;
      access_log off;
      expires 365d;
    }

    location /public/ {
      alias /app/public/;
      access_log off;
      expires 30d;
    }
  }
}